---
- include: "{{ ansible_os_family }}-setup.yml"
  tags:
    - bitbucket
    - bitbucket-packages
    - bitbucket-update

- name: Create system group
  group:
    name: "{{ bitbucket_group }}"
  tags:
    - bitbucket
    - bitbucket-account

- name: Create system user
  user:
    name: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
    home: "{{ bitbucket_datadir }}"
  tags:
    - bitbucket
    - bitbucket-account

- name: Set-up data-dir
  file:
    name: "{{ bitbucket_datadir }}/{{ bitbucket_version }}"
    owner: "{{ bitbucket_user  }}"
    group: "{{ bitbucket_group }}"
    state: directory
  tags:
    - bitbucket
    - bitbucket-update

- name: Install Bitbucket Server
  unarchive:
    src: "{{ bitbucket_url }}"
    dest: "{{ bitbucket_datadir }}/{{ bitbucket_version }}"
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
    extra_opts: "--strip-components=1"
    remote_src: yes
    creates: "{{ bitbucket_datadir }}/{{ bitbucket_version }}/bin/start-bitbucket.sh"
  notify: Restart bitbucket
  tags:
    - bitbucket
    - bitbucket-update

- name: Set ownership on related directories
  file:
    path: "{{ item }}"
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
    recurse: yes
    state: directory
  with_items:
    - "{{ bitbucket_datadir }}"
    - "{{ bitbucket_workdir }}"
  tags:
    - bitbucket
    - bitbucket-update

- name: Create shared directory
  file:
    path: "{{ bitbucket_workdir }}/shared"
    state: directory
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
  tags:
    - bitbucket
    - bitbucket-config
    - bitbucket-properties
    - bitbucket-update

- name: Deploy Bitbucket properties
  template:
    src: bitbucket.properties.j2
    dest: "{{ bitbucket_workdir }}/shared/bitbucket.properties"
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
    mode: "0664"
  notify: Restart bitbucket
  tags:
    - bitbucket
    - bitbucket-config
    - bitbucket-properties
    - bitbucket-update

- name: Deploy systemd unit file
  template:
    src: bitbucket.service.j2
    dest: /usr/lib/systemd/system/bitbucket.service
    owner: root
    group: root
  notify: Reload systemd and bitbucket
  tags:
    - bitbucket
    - bitbucket-update
    - bitbucket-config
    - bitbucket-service

- name: Enable service
  service:
    name: "bitbucket"
    enabled: "yes"
  notify: Restart bitbucket
  tags: 
    - bitbucket
